---
  ###
  ###
  # ROCKY LINUX OS Updates
  ###
  ###
  - name: Get pre-update kernel version
    ansible.builtin.shell: uname -nr
    register: pre_kernel_version

  - name: Display pre-update kernel version
    ansible.builtin.debug: msg="{{ pre_kernel_version.stdout_lines }}"


  - name: Log available updates to {{ logging_dir }} directory
    ansible.builtin.shell: yum check-update >> available_updates_`date +'%y%m%d-%H%M%S'`.txt
    args:
      chdir: "{{ logging_dir }}"
      warn: no
    register: yum_result
    failed_when: yum_result.rc not in [ 0, 100 ]
    when: logging_enabled_for_available_updates | bool


  - name: Check and install updates
    ansible.builtin.dnf:
      name: '*'
      state: latest
      update_cache: yes
    register: rocky_patched

  - pause:
      seconds: 5
    when: rocky_patched.changed


  - name: Verify if reboot is required
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required

  - name: Reboot host
    ansible.builtin.reboot:
      msg: "Reboot initiated by Ansible for OS Updates"
    async: 1
    poll: 0
    when:
      - rocky_patched.changed
      - reboot_required.stat.exists

  - name: Waiting for host to start...
    ansible.builtin.wait_for_connection:
      delay: 5 # seconds to wait before starting to poll
      connect_timeout: 20 # maximum number of seconds to wait for a connection to happen before closing and retrying
      sleep: 5 # seconds to sleep between checks
      timeout: 300 # maximum number of seconds to wait for
    when: rocky_patched.changed


  - name: Get post-update kernel version
    ansible.builtin.shell: uname -nr
    register: post_kernel_version
    when: rocky_patched.changed

  - name: Display post-update kernel version (only when version is different )
    ansible.builtin.debug: msg="{{ pre_kernel_version.stdout_lines }} -> {{ post_kernel_version.stdout_lines }}"
    when:
      - rocky_patched.changed
      - pre_kernel_version.stdout != post_kernel_version.stdout


  - name: Log installed updates to {{ logging_dir }} directory
    ansible.builtin.shell: rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" | cut -f 1 -d " " >> installed_updates_`date +'%y%m%d-%H%M%S'`.txt
    args:
      chdir: "{{ logging_dir }}"
      warn: no
    when:
      - logging_enabled_for_installed_updates | bool
      - rocky_patched.changed
