---
  ###
  ###
  # SETUP DOCKER SYSTEM PRUNE CRON
  ###
  - name: Remove /etc/cron.daily/docker-prune file if exists
    ansible.builtin.file:
      path: /etc/cron.daily/docker-prune
      state: absent

  - name: Cron to housekeep dangling images
    ansible.builtin.template:
      src: docker-prune.j2
      dest: /etc/cron.daily/docker-prune
      owner: root
      group: root
      mode: '0755'

  - name: Log rotate configuration for housekeep dangling images cron logs
    ansible.builtin.template:
      src: docker-logrotate.j2
      dest: /etc/logrotate.d/docker
      owner: root
      group: root
      mode: '0644'

  - name: Test housekeep dangling images cron
    ansible.builtin.shell: run-parts /etc/cron.daily
    args:
      executable: /bin/bash
    register: docker_cron

  - name: Show Cron Test (Output should be empty)
    ansible.builtin.debug: msg="{{ docker_cron.stdout_lines }}"