---
  ###
  ###
  # SETUP DOCKER COMPOSE
  ###
  - name: Install Docker Compose plugin
    ansible.builtin.package:
      name:
      - docker-compose-plugin
      state: latest

  - name: Get Docker Compose version
    ansible.builtin.shell: docker compose version
    args:
      executable: /bin/bash
    register: docker_compose_version

  - name: Show Docker Compose version
    ansible.builtin.debug: msg="{{ docker_compose_version.stdout_lines }}"
