---
  ###
  ###
  # SETUP DOCKER USER AND DIRECTORY
  ###
  - block:
    - name: Create user {{ docker_user }} to manage Docker
      ansible.builtin.user:
        name: "{{ docker_user }}"
        append: false
        comment: Docker User
        uid: 1005
        groups: docker
        password_lock: true
        expires: -1
        home: /home/{{ docker_user }}
        shell: /bin/bash
        state: present

    - name: Get User info
      ansible.builtin.shell: passwd -S {{ docker_user }}
      args:
        executable: /bin/bash
      register: docker_user

    - name: Show User info
      ansible.builtin.debug: msg="{{ docker_user.stdout_lines }}"

    when: docker_create_user | bool == true


  - block:
    - name: Create Docker directory
      ansible.builtin.file:
        path: "{{ docker_directory }}"
        state: directory
        owner: "{{ docker_directory_owner }}"
        group: docker
        mode: '0750'

    when: docker_create_directory | bool == true