---
# task file for linux-docker

- import_tasks: linux-docker-ip_forward.yml

- include_tasks: linux-docker-{{ ansible_distribution }}.yml

- import_tasks: linux-docker-user-directory.yml

- import_tasks: linux-docker-system-prune-cron.yml
  when: docker_system_prune_cron | bool == true